version: '3.7'

services:
  redis:
    image: "redis"
    networks:
      - microengine-webhooks
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  microengine-integration:
    build:
      context: ../
      dockerfile: docker/integration.Dockerfile
    ports:
      - "5000:5000"
    networks:
      - microengine-webhooks
      - default
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=00000000000000000000000000000000
      - WEBHOOK_URL=http://microengine-webhooks-psc:8080/
  arbiter-integration:
    build:
      context: ../
      dockerfile: docker/integration.Dockerfile
    ports:
      - "6000:5000"
    networks:
      - microengine-webhooks
      - default
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=00000000000000000000000000000000
      - WEBHOOK_URL=http://arbiter-webhooks-psc:8080/
  microengine-webhooks-psc:
    depends_on:
      - redis
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks:
      - microengine-webhooks
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=00000000000000000000000000000000
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=text
      - HOST=0.0.0.0
      - PORT=8080
      - REDIS=redis:6379
      - QUEUE=microengine
      - BACKEND=producer
      - COMMAND=microengine
  arbiter-webhooks-psc:
    depends_on:
      - redis
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks:
      - microengine-webhooks
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=00000000000000000000000000000000
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=text
      - HOST=0.0.0.0
      - PORT=8080
      - REDIS=redis:6379
      - QUEUE=arbiter
      - BACKEND=producer
      - COMMAND=arbiter
  microengine-worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks:
      - microengine-webhooks
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_ADDR=redis:6379
      - QUEUE=microengine
      - BACKEND=eicar
      - COMMAND=worker
  arbiter-worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks:
      - microengine-webhooks
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_ADDR=redis:6379
      - QUEUE=arbiter
      - BACKEND=eicar
      - COMMAND=worker

networks:
  microengine-webhooks:
    driver: bridge
