version: '3.7'

services:
  redis:
    image: "redis"
    networks:
      - polyswarmclient-webhooks
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  integration:
    build:
      context: ../
      dockerfile: docker/integration.Dockerfile
    ports:
      - "5000:5000"
    networks:
      - polyswarmclient-webhooks
      - default
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=00000000000000000000000000000000
      - WEBHOOK_URL=http://psc-webhooks:8080/
  psc-webhooks:
    depends_on:
      - redis
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks:
      - polyswarmclient-webhooks
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=00000000000000000000000000000000
      - LOG_LEVEL=INFO
      - CLIENT_LOG_LEVEL=INFO
      - LOG_FORMAT=text
      - HOST=0.0.0.0
      - PORT=8080
      - REDIS_ADDR=redis:6379
      - QUEUE=microengine
      - BACKEND=eicar
      - COMMAND=arbiter
  microengine-worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks:
      - polyswarmclient-webhooks
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_ADDR=redis:6379
      - QUEUE=microengine
      - BACKEND=eicar
      - COMMAND=worker

networks:
  polyswarmclient-webhooks:
    driver: bridge
